# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0133f55521a693c327aef0bf7e7a0c9c5ef49b6dc54343d3165354be954eeffe92374b367cc155bdcce3cf32d01187ee51ceb7af41e58f22a13f3aa21f8fa29

test:
  secret_key_base: 8e3b7a5bed34e5066f9eda799ff789783e6bf1372cc74c5d1283794af8f61628e069e9371294bad654575a75447138e356e9b1cd51283f5bdad3b4819f2ce682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
